export interface DatosUsuario {
  id: number,
  primer_nombre: any,
  segundo_nombre: any,
  apellido_paterno: any,
  apellido_materno: any,
  rut: any,
  email: any,
  email_comercial: any,
  celular: any,
  telefono: any,
  calle: any,
  numero_calle: any,
  ciudad: any,
  comuna: any,
  region: any,
  calle_comercial: any,
  numero_calle_comercial: any,
  oficina: any,
  ciudad_comercial: any,
  comuna_comercial: any,
  region_comercial: any,
}